# Generated by Django 4.1.7 on 2023-04-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohs_app', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
